### PR TITLE
Improve design of customer index rows

### PR DESCRIPTION
**Pull request by patdryburgh**
The customer index rows are how Saccos will navigate to a customer's profile. These lists need to be easily scannable so the user doesn't have to spend too much time deciphering who each customer is. By improving the visual hierarchy, we can make finding the right individual far easier on our users.

Before:

screen shot 2017-03-23 at 2 24 52 pm

After: 

screen shot 2017-03-23 at 3 06 28 pm

### CODE REVIEW

**Comment by patdryburgh** [comment]
The other improvement made is that now the user can click almost anywhere in the row to bring up the profile, whereas before only the photo and name were clickable. I've introduced a `.js-prevent-data-toggle` class which prevents elements with that class from propagating to their parent if their parent has a `data-toggle` attribute. 

The reason for this is that it prevents the modal from appearing if the user clicks on the email address, though it could apply to other links added to these types of rows, as well. The only time it doesn't work is when the element you are wishing to exclude is itself a modal toggle (i.e. the “Delete” button).

**Comment by coreysan** [comment]
Great work - what do you think about the H4>name above the customer number? 

The address being higher than the row title feels slightly unbalanced

See these two rows for comparison:
screen shot 2017-03-23 at 3 19 24 pm

**Comment by patdryburgh** [comment]
Yeah, I do like that better but think the name and account number should be closer together. Will push a change for that in a moment.

**Comment by patdryburgh** [comment]
@coreysan I've updated this PR to reflect our discussed changes. See below:

screen shot 2017-03-23 at 3 59 38 pm

**Comment by coreysan** [comment]
Beautiful, thanks Pat.

**Pull request merged**
